name: Keep Render Service Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # alle 5 Minuten (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    concurrency:
      group: keepalive
      cancel-in-progress: false
    steps:
      - name: Call Render Health Endpoint
        run: |
          curl -sS --max-time 10 https://pdf-service-1.onrender.com/health || true
